import pandas as pd
import numpy as np
df = pd.read_csv("01_Dataset/Nassau Candy Distributor.csv")
print("Original Dataset Shape:", df.shape)
df["Order Date"] = pd.to_datetime(df["Order Date"],format="%d-%m-%Y",errors="coerce")
df["Ship Date"] = pd.to_datetime(df["Ship Date"],format="%d-%m-%Y",errors="coerce")
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:", df.duplicated().sum())
df = df.drop_duplicates()
print("\nInvalid Numerical Values:")
print("Sales <= 0:", (df["Sales"] <= 0).sum())
print("Units <= 0:", (df["Units"] <= 0).sum())
print("Cost < 0:", (df["Cost"] < 0).sum())
print("\nOrder Date Range:")
print(df["Order Date"].min(), "to", df["Order Date"].max())
print("\nShip Date Range:")
print(df["Ship Date"].min(), "to", df["Ship Date"].max())
lead_time_check = (df["Ship Date"] - df["Order Date"]).dt.days
print("\nLead Time Validation:")
print(lead_time_check.describe())
print("\nLead Times Greater Than 30 Days:",(lead_time_check > 30).sum())
df.to_csv("01_Dataset/Nassau_Candy_Cleaned.csv",index=False)
print("\nCleaned Dataset Shape:", df.shape)
print("Cleaned dataset saved successfully.")