import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("01_Dataset/Nassau_Candy_Featured.csv")
print("Dataset loaded successfully.")
print("Dataset Shape:", df.shape)
print("\n===== BUSINESS SUMMARY =====")
print("Total Sales:", round(df["Sales"].sum(), 2))
print("Total Gross Profit:", round(df["Gross Profit"].sum(), 2))
print("Total Cost:", round(df["Cost"].sum(), 2))
print("Total Units Sold:", df["Units"].sum())
print("Total Orders:", df["Order ID"].nunique())
print("Total Products:", df["Product ID"].nunique())
print("Average Profit Margin %:",round(df["Profit Margin %"].mean(), 2))
region_analysis = df.groupby("Region").agg(Total_Sales=("Sales", "sum"),Total_Profit=("Gross Profit", "sum"),Total_Units=("Units", "sum"),Total_Orders=("Order ID", "nunique")).sort_values("Total_Sales", ascending=False)
print("\n===== REGION ANALYSIS =====")
print(region_analysis.round(2))
region_sales = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)
plt.figure(figsize=(8, 5))
region_sales.plot(kind="bar")
plt.title("Total Sales by Region")
plt.xlabel("Region")
plt.ylabel("Total Sales")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
product_analysis = df.groupby("Product Name").agg(Total_Sales=("Sales", "sum"),Total_Profit=("Gross Profit", "sum"),Total_Units=("Units", "sum")).sort_values("Total_Sales", ascending=False)
print("\n===== TOP 10 PRODUCTS BY SALES =====")
print(product_analysis.head(10).round(2))
top10_products = product_analysis.head(10)
plt.figure(figsize=(12, 6))
top10_products["Total_Sales"].plot(kind="bar")
plt.title("Top 10 Products by Sales")
plt.xlabel("Product Name")
plt.ylabel("Total Sales")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()
ship_mode_analysis = df.groupby("Ship Mode").agg(Total_Sales=("Sales", "sum"),Total_Profit=("Gross Profit", "sum"),Total_Units=("Units", "sum"),Total_Orders=("Order ID", "nunique")).sort_values("Total_Sales", ascending=False)
print("\n===== SHIP MODE ANALYSIS =====")
print(ship_mode_analysis.round(2))
plt.figure(figsize=(8, 5))
ship_mode_analysis["Total_Sales"].plot(kind="bar")
plt.title("Total Sales by Ship Mode")
plt.xlabel("Ship Mode")
plt.ylabel("Total Sales")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()