import pandas as pd
df = pd.read_csv("01_Dataset/Nassau_Candy_Featured.csv")
df["Order Date"] = pd.to_datetime(df["Order Date"], errors="coerce")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], errors="coerce")
print("===== SHIPPING DATE INVESTIGATION =====")
print("\nDataset Shape:")
print(df.shape)
print("\nOrder Date Range:")
print(df["Order Date"].min(), "to", df["Order Date"].max())
print("\nShip Date Range:")
print(df["Ship Date"].min(), "to", df["Ship Date"].max())
print("\nOrder Year Distribution:")
print(df["Order Date"].dt.year.value_counts().sort_index())
print("\nShip Year Distribution:")
print(df["Ship Date"].dt.year.value_counts().sort_index())
df["Current Lead Time"] = (df["Ship Date"] - df["Order Date"]).dt.days
print("\nCurrent Lead Time Statistics:")
print(df["Current Lead Time"].describe())
print("\nAverage Lead Time by Ship Mode:")
print(df.groupby("Ship Mode")["Current Lead Time"].agg(["count", "mean", "min", "max"]).round(2))
print("\nSample Shipping Records:")
print(df[ ["Order ID", "Order Date", "Ship Date","Ship Mode", "Current Lead Time"]].head(20).to_string(index=False))