import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("01_Dataset/Nassau_Candy_Factory_Mapped.csv")
print("Dataset loaded successfully.")
print("Dataset Shape:", df.shape)
factory_analysis = df.groupby("Factory").agg(
Total_Sales=("Sales", "sum"),Total_Profit=("Gross Profit", "sum"),Total_Cost=("Cost", "sum"),
Total_Units=("Units", "sum"),Total_Orders=("Order ID", "nunique"),Total_Products=("Product Name", "nunique"))
factory_analysis["Profit_Margin_%"] = (factory_analysis["Total_Profit"]/ factory_analysis["Total_Sales"]) * 100
factory_analysis = factory_analysis.sort_values("Total_Sales",ascending=False)
print("\n===== FACTORY PERFORMANCE ANALYSIS =====")
print(factory_analysis.round(2))
best_sales_factory = factory_analysis["Total_Sales"].idxmax()
print("\nHighest Sales Factory:")
print(best_sales_factory)
best_profit_factory = factory_analysis["Total_Profit"].idxmax()
print("\nHighest Profit Factory:")
print(best_profit_factory)
plt.figure(figsize=(10, 6))
factory_analysis["Total_Sales"].plot(kind="bar")
plt.title("Total Sales by Factory")
plt.xlabel("Factory")
plt.ylabel("Total Sales")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 6))
factory_analysis["Total_Profit"].plot(kind="bar")
plt.title("Total Gross Profit by Factory")
plt.xlabel("Factory")
plt.ylabel("Gross Profit")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.show()