import pandas as pd
df = pd.read_csv("01_Dataset/Nassau_Candy_Factory_Mapped.csv")
print("Dataset loaded successfully.")
print("Dataset Shape:", df.shape)
print("\n===== CUSTOMER LOCATION ANALYSIS =====")
print("\nUnique Countries:")
print(df["Country/Region"].value_counts())
print("\nNumber of Unique States:")
print(df["State/Province"].nunique())
print("\nNumber of Unique Cities:")
print(df["City"].nunique())
print("\nNumber of Unique Postal Codes:")
print(df["Postal Code"].nunique())
locations = df[["Country/Region","State/Province","City","Postal Code","Region"]].drop_duplicates()
print("\nUnique Destination Locations:")
print(len(locations))
print("\nFirst 20 Locations:")
print(locations.head(20).to_string(index=False))
print("\n===== ORDERS BY REGION =====")
region_orders = (df.groupby("Region")["Order ID"].nunique().sort_values(ascending=False))
print(region_orders)
locations.to_csv("01_Dataset/Customer_Locations.csv",index=False)
print("\nCustomer location file created successfully.")
print("Saved: 01_Dataset/Customer_Locations.csv")